### ISSUE TITLE
What was the problem with np for v8.0.0-beta.3?

### ISSUE THREAD

**Issue by papb** [squirrellyjs/squirrelly#144]
> *Note: unfortunately, due to some problems with np, there was an error in publishing beta 3 and we had to skip to beta 4.* ([source](https://github.com/squirrellyjs/squirrelly/releases/tag/v8.0.0-beta.4))

May I ask what was the problem? And how did you work around it? Is this being tracked in the [np repository](https://github.com/sindresorhus/np) already? (From a cursory look there I didn't find anything...) Is this a regression on np?

Let's make np better :)

**Comment by nebrelbug** [comment]
Hi @papb! The problem was mainly user error. I updated `np`, and didn't realize it now required input of the 2FA code. So, to me, it looked like it was lagging infinitely :)

I canceled `np` because I thought it was frozen, but `v8.0.0-beta.3` was already tagged on GitHub and I decided to just publish one version higher.

**Comment by papb** [comment]
@nebrelbug Ah I see, thanks for your time :)
