### ISSUE TITLE
Partials does not work in Electron

### ISSUE THREAD

**Issue by jenstornell** [squirrellyjs/squirrelly#192]
I have placed the file `mypartial.html` in the root of Electron which runs with node. 

>Uncaught Squirrelly Error: Could not fetch template "./mypartial.html"

```js
var Sqrl = require("squirrelly");
var results = Sqrl.render(
      `
      {{@include("./mypartial.html")/}}
      Hi {{it.user}}
    `,
      { user: "Ada Lovelace" }
);
console.log(results);
```

**Comment by nebrelbug** [comment]
Hmm, I'm not sure why this would be happening.

Can you try doing `{{@include("mypartial.html")/}}`?

I'm guessing Electron uses a different root folder.

**Comment by VictorAyalaMX** [comment]
I had the same issue with nodejs, In my case the confusion happened because [this doc page](https://squirrelly.js.org/docs/syntax/partials) never mentions we are supposed to define partials in advance during Squirrelly setup:

```
app.set('view engine', 'squirrelly')
app.set('views', './views')
Sqrl.templates.define("footer", Sqrl.compile("This is my footer"));
```

The above is explained in the [last page](https://squirrelly.js.org/docs/api/templates-partials-layouts) of the documentation. 


@nebrelbug 
**Question**: How can I define a Partial from an existing template file without having to open the file template file to read and pass all the content as a string value? 

Thank you.

**Comment by nebrelbug** [comment]
Hi @VictorAyalaMX, great question (and sorry for the poor documentation).

Actually, you should be able to use `{{@ includeFile('../footer.html', {data: ...}) /}}`. Note that for this to work you'll have to pass the `filename` option in the configuration of the template file you're rendering (if you're using Express this works automatically)

Embarrassingly, it looks like I didn't actually document that at all :grimacing: 

Anyway, hope that helps :smile:.
